/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package rc4;

/**
 *
 * @author randozero
 */
public class main extends javax.swing.JFrame {

    public String xor(String x,String y){
        String hasil="";
        System.out.println("x adalah "+x+" y adalah "+y);
        if(x.equals(y)){
            hasil = "0";
        }else{
            hasil = "1";
        }
        return hasil;
    }
    
    
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TF_input_text = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TF_output_text = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        TF_array_K = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TF_kunci = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        log_kunci = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        log_enkripsi = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("enkripsi/dekripsi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Input");

        jLabel2.setText("output");

        TF_output_text.setEnabled(false);

        jLabel3.setText("Array K");

        jButton2.setText("Buat");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Kunci");

        log_kunci.setColumns(20);
        log_kunci.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        log_kunci.setRows(5);
        jScrollPane1.setViewportView(log_kunci);

        jLabel5.setText("Log Kunci");

        log_enkripsi.setColumns(20);
        log_enkripsi.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        log_enkripsi.setRows(5);
        jScrollPane2.setViewportView(log_enkripsi);

        jLabel6.setText("Log enkripsi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TF_input_text)
                                    .addComponent(TF_output_text, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TF_array_K)
                                    .addComponent(TF_kunci, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2))
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_array_K, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TF_kunci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_input_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TF_output_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String K = TF_array_K.getText();
        String S = "";
        for(int i=0;i<K.length();i++){
            S+= i+"";
        }
        String log = "array K = "+K+"\narray S = "+S+"\n";
        log += "\npeng-array-an KSA\n"
                + "j=( j + S[i] + K [ i mod K.length() ]) mod K.length() )\n"
                + "swap S[i],S[j]\n\n";
        log_kunci.setText(log);
        int j=0;
        for (int i = 0; i < K.length(); i++) {
            log+="iterasi ke-"+i+"\n"
                    + "i ="+i
                    + " j ="+j+"\n";
            String s = S.charAt(i)+"";
            int mod =i % K.length();
            String k = K.charAt(mod)+"";
            log+="i="+i+"\n"
                    + "j=("+j+"+"+s+"+"+k+") mod "+K.length()+"\n";
            j =( j + Integer.parseInt(s) + Integer.parseInt(k) ) % K.length();
            log+="j="+j+"\n"
                    + "swap S["+i+"] "+"S["+j+"]\n";
            System.out.println("i = "+i+" j = "+j+" s = "+s+" k ="+k+" k lenght = "+K.length());
            char temp=S.charAt(i);
            String newS="";
            for(int z =0;z<S.length();z++){
                if(z==i){
                    newS+=S.charAt(j)+"";
                }else if(z==j){
                    newS+=temp+"";
                }else{
                    newS+=S.charAt(z);
                }
            }
            S=newS;
            log+= "S="+S+"\n\n";
            log_kunci.setText(log);
        }
        log_kunci.setText(log);
        TF_kunci.setText(S);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String Key = TF_kunci.getText();
        String Enkrip = TF_input_text.getText();
        String log = "kunci = "+Key+"\n"
                + "membuat kunci baru lagi dengan rumus\n"
                + "i = (i+1) mod kunci.length\n"
                + "j = (j+kunci[i]) mod kunci.length\n"
                + "swap (kunci[i],kunci[j])\n"
                + "chiper key = kunci[(kunci[i]+kunci[j]) mod keylength]\n\n";
        String total="";
        int j=0;
        int l=0;
        for (int i = 0; i < Key.length(); i++) {
            log+="iterasi ke-"+i+"\n"
                    + "i = "+l+" j = "+j+"\n";
            l = (i+1)%Key.length();
            log+= "i = ("+i+" + 1) mod "+Key.length()+"\n"
                    + "i ="+l+"\n";
            String key = Key.charAt(l)+"";
            log+="j = ("+j+" + "+key+") mod "+Key.length()+"\n";
            j = (j+Integer.parseInt(key))%Key.length();
            log+="j = "+j+"\n"
                    + "swap(kunci["+l+"] , kunci["+j+"])\n";
            char temp = Key.charAt(l);
            String newS="";
            for(int z =0;z<Key.length();z++){
                if(z==l){
                    newS+=Key.charAt(j)+"";
                }else if(z==j){
                    newS+=temp+"";
                }else{
                    newS+=Key.charAt(z);
                }
            }
            Key =newS;
            temp = Key.charAt(l);
            char temp2 = Key.charAt(j);
            log+="kunci berubah = "+newS+"\n"
                    + "hasil chiper key = kunci[("+temp+"+"+temp2+") mod "+Key.length()+"]\n";
            int coba =(Integer.parseInt(temp+"")+Integer.parseInt(temp2+"")) % Key.length();
            String a = newS.charAt(coba)+"";
            log+="hasil chiper key = "+a+"\n\n";
            total +=a;
        }
        log_enkripsi.setText(log);
        log += "kata = "+Enkrip+"\n"
                + "Chiper key = "+total+"\n\n"
                + "XOR biner antara kunci dan kata\n\n";
        String hasil="";
        
        for(int i=0;i<Enkrip.length();i++){
            String x = Integer.toBinaryString(Enkrip.charAt(i));
            String y = Integer.toBinaryString(Integer.parseInt(total.charAt(i)+""));
            String newY="";
            for(int k=0;k<x.length()-y.length();k++){
                newY+="0";
            }
            newY+=y;
            y=newY;
            log+= "kata["+i+"] "+"  XOR  kunci["+i+"]\n"
                    + x +"        "+y+"\n";
            String hasilxor="";
            
            for (int k = 0; k < x.length(); k++) {
                String XOR=xor(x.charAt(k)+"",y.charAt(k)+"");
                System.out.println(XOR);
                hasilxor+=XOR;
            }
            
            System.out.println("\n hasilXOR = "+hasilxor);
            
            String huruf = (char)Integer.parseInt(hasilxor, 2)+"";
            log+= "hasilnya ="+hasilxor+"\n";
            log+= "hurufnya ="+huruf+"\n\n";
            hasil+=huruf;
            log_enkripsi.setText(log);
        }
        log+= "hasil enkripsi = "+hasil;
        TF_output_text.setText(hasil);
        log_enkripsi.setText(log);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TF_array_K;
    private javax.swing.JTextField TF_input_text;
    private javax.swing.JTextField TF_kunci;
    private javax.swing.JTextField TF_output_text;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea log_enkripsi;
    private javax.swing.JTextArea log_kunci;
    // End of variables declaration//GEN-END:variables
}
